name: ioponic
version: 1.0.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  hawk_fab_menu: ^1.2.0
  google_fonts: ^6.2.0
  flutter_datetime_picker_bdaya: ^3.0.2
  persistent_bottom_nav_bar_v2: ^5.2.3
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  win32: ^5.13.0
  shared_preferences: ^2.5.3
  marquee: ^2.3.0



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/home_icons/
    - assets/images/schedule/
    - assets/images/logo/
    - assets/images/blobs/
    - assets/images/home/
    - assets/images/education/
    - assets/images/about/
    - assets/icons/
    - assets/gif/

